const $=id=>document.getElementById(id),labels={missing:'未采集',pending:'原图待处理',review:'待人工审核',approved:'审核通过待交付',delivered:'已交付',delivered_updated:'已交付后照片变化',machine_rejected:'机器退回',review_rejected:'人工退回',failed:'处理失败'};
labels.processing='处理任务未完成';
let engineUrls=[],students=[],selected=new Set(),config={},current=null,plan=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body,method='POST'){const options=body===undefined?{}:{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body)};const r=await fetch('/api/v1/'+path,options);const data=await r.json();if(!r.ok)throw Error(data.message||JSON.stringify(data.detail));return data;}
function notice(e){const text=e instanceof Error?e.message:e;$('notice').textContent=text;if($('detail').open)$('detailNote').textContent=text;if(e instanceof Error&&$('plan').open)$('planSummary').textContent=text;}
function on(id,fn){$(id).onclick=async()=>{try{await fn();}catch(e){notice(e);}};}
function show(page){document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==page);document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===page?'page':'false'));$('title').textContent=document.querySelector(`[data-page="${page}"]`).textContent;}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
function art(a){return a?'/api/v1/artifacts/'+a.id:'';}
function image(a){return a?`<a href="${art(a)}" target="_blank"><img src="${art(a)}" loading="lazy" alt="照片预览"></a>`:'<p>暂无照片</p>';}
function visible(){return students.filter(s=>(!$('filter').value||s.status===$('filter').value)&&s.id.includes($('search').value.trim()));}
function render(){const rows=visible();$('counts').innerHTML=Object.entries(labels).map(([k,v])=>`<button data-filter="${k}">${v} <b>${students.filter(s=>s.status===k).length}</b></button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{$('filter').value=b.dataset.filter;render();});$('cards').innerHTML=rows.map(s=>`<article class="card"><label><input type="checkbox" data-id="${esc(s.id)}" ${selected.has(s.id)?'checked':''}> ${esc(s.id)}</label>${image(s.result?.artifact||s.source)}<p>${labels[s.status]}</p><button data-detail="${esc(s.id)}">查看流程 / 审核</button></article>`).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id);$('selection').textContent=`已选 ${selected.size} 人`;});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openStudent(b.dataset.detail).catch(notice));$('selection').textContent=`已选 ${selected.size} 人`;$('all').checked=rows.length>0&&rows.every(s=>selected.has(s.id));}
$('filter').innerHTML='<option value="">全部状态</option>'+Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('filter').onchange=render;$('search').oninput=()=>{show('students');render();};$('all').onchange=()=>{visible().forEach(s=>$('all').checked?selected.add(s.id):selected.delete(s.id));render();};
async function refresh(){students=await api('students');render();await refreshJobs();await refreshDeliveries();}
on('refresh',refresh);
async function openStudent(id){current=await api('students/'+encodeURIComponent(id));$('studentTitle').textContent=id;$('studentState').textContent=labels[current.status];const source=current.sources.at(-1),result=current.results.filter(r=>r.source_id===source?.id).at(-1);current.result=result;$('comparison').innerHTML=`<figure>${image(source)}<figcaption>原始照片 ${source?source.width+'×'+source.height:''}</figcaption></figure><figure>${image(result?.artifact)}<figcaption>当前成片 ${result?.artifact?result.artifact.width+'×'+result.artifact.height:''}</figcaption></figure>`;stages(result);$('history').textContent=JSON.stringify({history:current.history,versions:current.results,delivered:current.delivered},null,2);$('approve').disabled=!result?.artifact||current.status.startsWith('delivered');$('reject').disabled=$('approve').disabled;$('undo').disabled=$('approve').disabled;$('detailNote').textContent='点击图片可打开原尺寸预览。跳过只切换照片，不写入审核状态。';if(!$('detail').open)$('detail').showModal();}
function stages(result){const statuses={passed:'通过',disabled:'未启用',adjusted:'已调整',rejected:'未通过',skipped:'已跳过',success:'完成'};$('stages').innerHTML=(result?.stages||[]).map(s=>`<article><b>${esc(s.label)}</b>${image(s.artifact)}<p>${esc(statuses[s.status]||s.status)} · ${esc(s.detail)}</p></article>`).join('');}
on('closeDetail',()=>$('detail').close());
async function navigate(delta){const rows=visible(),index=rows.findIndex(s=>s.id===current.id);if(rows[index+delta])await openStudent(rows[index+delta].id);}
on('previous',()=>navigate(-1));on('next',()=>navigate(1));
async function review(decision){let reason='';if(decision==='rejected'){reason=prompt('退回原因');if(reason===null)return;}await api('reviews',{student_id:current.id,result_id:current.result.id,decision,expected_revision:current.revision,reason});await refresh();await openStudent(current.id);notice('审核已保存');}
on('approve',()=>review('approved'));on('reject',()=>review('rejected'));on('undo',()=>review('pending'));
on('replace',async()=>{const reason=prompt('启动替换流程的原因（保留历史交付记录）');if(reason){await api('students/'+current.id+'/replacement',{reason});await refresh();await openStudent(current.id);}});
on('preview',async()=>{notice('正在试处理；预览不会改变当前审核');const result=await api('students/'+current.id+'/preview',readConfig());stages(result);$('detailNote').textContent='以下为试处理结果，未作为正式成片保存。正式执行请返回学生列表创建处理任务。';notice('试处理完成');});
on('saveRoster',async()=>{await api('roster',{student_ids:$('roster').value.split(/[\s,，]+/).filter(Boolean)});await refresh();notice('名单已添加');});
async function xlsx(inspect){const f=$('xlsx').files[0];if(!f)throw Error('请选择Excel');const body=new FormData();body.append('file',f);for(const [k,id] of [['sheet','sheet'],['header_row','headerRow'],['id_column','idCol'],['image_column','imageCol']])body.append(k,$(id).value);body.append('inspect_only',inspect);notice('正在读取表格');const result=await api('imports/xlsx',body);if(inspect&&result.id_column){$('idCol').value=result.id_column;$('imageCol').value=result.image_column;}$('importResult').textContent=JSON.stringify(result,null,2);await refresh();if(!inspect)show('jobs');notice(inspect?`表格检查完成，已使用学号列 ${result.id_column}、图片列 ${result.image_column}`:'已创建后台原图接收任务');}
on('inspectXlsx',()=>xlsx(true));on('importXlsx',()=>xlsx(false));
on('uploadPhotos',async()=>{for(const f of $('photos').files){const body=new FormData();body.append('photo',f);notice('上传 '+f.name);await api('students/'+encodeURIComponent(f.name.replace(/\.[^.]+$/,''))+'/photos',body);}await refresh();notice('照片上传完成');});
async function migrate(apply){$('migrationResult').textContent=JSON.stringify(await api('migrations/legacy',{path:$('legacy').value,apply}),null,2);if(apply)await refresh();}
on('checkLegacy',()=>migrate(false));on('migrateLegacy',()=>migrate(true));
const names={quality_enabled:'启用内置预检',auto_orient:'校正90/180/270度方向',check_grayscale:'黑白检查',check_face:'人脸检查',check_glare:'反光检查',check_recapture:'翻拍检查',background_mode:'图像处理引擎',background_color:'背景颜色',crop_enabled:'最终裁切并缩放',crop_width:'最终宽度（像素）',crop_height:'最终高度（像素）',hivision_url:'Hivision API地址',hivision_timeout:'API超时（秒）',hivision_width:'Hivision标准图宽',hivision_height:'Hivision标准图高',hivision_hd:'使用高清返回',hivision_face_align:'Hivision小角度对齐',hivision_matting_model:'Hivision抠图模型',hivision_face_model:'Hivision人脸模型',hivision_dpi:'打印DPI',stop_on_reject:'预检不通过时停止',grayscale_ratio_threshold:'黑白比例阈值',grayscale_delta_limit:'灰度色差阈值',face_confidence_threshold:'人脸置信度阈值',glare_ratio_threshold:'反光比例阈值',glare_luma_threshold:'过曝亮度阈值',recapture_score_threshold:'翻拍分数阈值',orientation_min_confidence:'方向最低置信度',orientation_confidence_margin:'旋转置信度优势',hivision_head_measure_ratio:'面部占比',hivision_head_height_ratio:'面部中心高度',hivision_top_distance_max:'头顶留白最大比例',hivision_top_distance_min:'头顶留白最小比例',hivision_brightness_strength:'亮度调整',hivision_contrast_strength:'对比度调整',hivision_sharpen_strength:'锐化调整',hivision_saturation_strength:'饱和度调整'};
const configGroups=[
 ['原图预检','启用内置预检后执行以下检查；阈值与对应检查放在一起。',['quality_enabled','stop_on_reject','auto_orient','orientation_min_confidence','orientation_confidence_margin','check_grayscale','grayscale_ratio_threshold','grayscale_delta_limit','check_face','face_confidence_threshold','check_glare','glare_ratio_threshold','glare_luma_threshold','check_recapture','recapture_score_threshold']],
 ['背景处理','选择处理引擎；不处理背景时保留原背景。',['background_mode','background_color']],
 ['Hivision · 服务与模型','仅在选择 Hivision 引擎时使用。接口测试只检查连接，不上传照片。',['hivision_url','hivision_timeout','hivision_matting_model','hivision_face_model']],
 ['Hivision · 尺寸与构图','标准图尺寸与最终输出尺寸独立；高清返回仍会受最终裁切设置影响。',['hivision_width','hivision_height','hivision_dpi','hivision_hd','hivision_face_align','hivision_head_measure_ratio','hivision_head_height_ratio','hivision_top_distance_min','hivision_top_distance_max']],
 ['Hivision · 画面调整','保留 0 使用默认效果。建议先在单张照片上试处理。',['hivision_brightness_strength','hivision_contrast_strength','hivision_sharpen_strength','hivision_saturation_strength']],
 ['最终输出','在背景处理之后执行；开启后按以下宽高裁切并缩放。',['crop_enabled','crop_width','crop_height']]
];
function drawConfig(){
 const choices={background_mode:['none','ai','quick','hivision'],hivision_matting_model:['modnet_photographic_portrait_matting','hivision_modnet','birefnet-v1-lite','rmbg-1.4','mnn_hivision_modnet'],hivision_face_model:['mtcnn','retinaface-resnet50','face_plusplus']};
 const engineNames={none:'不处理背景',ai:'本地 AI 抠图',quick:'快速纯色替换',hivision:'Hivision 服务'};
 $('configFields').innerHTML=configGroups.map(([title,help,keys])=>`<fieldset class="config-group"><legend>${title}</legend><p>${help}</p><div class="config-grid">${keys.map(k=>{const v=config[k];return `<label class="${typeof v==='boolean'?'toggle-field':''}"><span>${esc(names[k]||k)}</span>${choices[k]?`<select data-config="${k}">${choices[k].map(x=>`<option value="${x}" ${x===v?'selected':''}>${esc(engineNames[x]||x)}</option>`).join('')}</select>`:`<input data-config="${k}" type="${typeof v==='boolean'?'checkbox':typeof v==='number'?'number':'text'}" ${typeof v==='boolean'?(v?'checked':''):`value="${esc(v)}"`} step="any">`}</label>`;}).join('')}</div>${keys.includes('hivision_url')?'<div class="engine-tools"><label>历史 API 地址 <select data-engine-history><option value="">选择已保存的地址</option></select></label><div class="toolbar"><button data-engine-add>添加当前地址到历史</button><button data-engine-test>测试当前 API（不上传照片）</button></div><p>切换后点击保存配置，供下次运行使用。历史地址保存在当前工作区。</p><p data-engine-message role="status"></p></div>':''}</fieldset>`).join('');
 bindEngineTools($('configFields'));
}
function bindEngineTools(container){
 const select=container.querySelector('[data-engine-history]'),input=container.querySelector('[data-config="hivision_url"]');
 select.innerHTML='<option value="">选择已保存的地址</option>'+engineUrls.map(url=>`<option value="${esc(url)}">${esc(url)}</option>`).join('');
 select.value=engineUrls.includes(input.value)?input.value:'';
 const message=container.querySelector('[data-engine-message]');
 select.onchange=()=>{if(select.value){input.value=select.value;input.dispatchEvent(new Event('input'));message.textContent='已切换地址，保存配置后下次运行会继续使用。';}};
 container.querySelector('[data-engine-add]').onclick=async()=>{try{engineUrls=await api('engines/hivision/urls',{url:input.value});document.querySelectorAll('#configFields,#previewFields').forEach(c=>{if(c.querySelector('[data-engine-history]'))bindEngineTools(c);});message.textContent='地址已保存到历史。';}catch(e){message.textContent=e.message;}};
 container.querySelector('[data-engine-test]').onclick=async()=>{message.textContent='正在测试当前地址…';try{message.textContent=JSON.stringify(await api('engines/hivision/test',{url:input.value}));}catch(e){message.textContent=e.message;}};
}
function readConfig(){const c={};document.querySelectorAll('#configFields [data-config]').forEach(e=>{c[e.dataset.config]=e.type==='checkbox'?e.checked:e.type==='number'?Number(e.value):e.value;});return c;}
on('saveConfig',async()=>{config=await api('config',readConfig(),'PUT');notice('运行配置已保存');});
function saveFile(name,value){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
on('downloadConfig',()=>saveFile('StudentPhotoFlow配置.json',readConfig()));on('loadConfig',async()=>{config=await api('config',JSON.parse(await $('configFile').files[0].text()),'PUT');drawConfig();notice('配置已导入并保存');});
async function replan(){if(!selected.size)throw Error('请先选中学生');plan=await api('processing-jobs',{student_ids:[...selected],config:readConfig(),new_version:$('newVersion').checked,dry_run:true});$('planSummary').textContent=`执行 ${plan.items.filter(x=>x.execute).length} 人；跳过 ${plan.items.filter(x=>!x.execute).length} 人`;$('planRows').textContent=plan.items.map(x=>x.student_id+'：'+(x.execute?'将处理':x.reason)).join('\n');}
on('process',async()=>{await replan();$('plan').showModal();});on('replan',replan);on('closePlan',()=>$('plan').close());on('startJob',async()=>{await api('processing-jobs',{student_ids:plan.items.map(x=>x.student_id),config:plan.config,new_version:$('newVersion').checked,dry_run:false,expected_revision:plan.revision});$('plan').close();show('jobs');await refreshJobs();});
const jobLabels={running:'运行中',pausing:'正在暂停',paused:'已暂停',cancelling:'正在中断',cancelled:'已中断',interrupted:'异常中断，可恢复',completed:'已结束'};
async function refreshJobs(){$('jobList').innerHTML=(await api('jobs')).map(j=>`<article><b>${esc(j.id.slice(0,8))} · ${jobLabels[j.status]}</b><p>完成 ${j.completed.length} / ${j.plan.items.filter(x=>x.execute).length}；当前 ${esc(j.current||'—')}；失败 ${Object.keys(j.errors).length}</p>${['pause','resume','cancel'].map(a=>`<button data-job="${j.id}" data-action="${a}">${{pause:'暂停',resume:'继续未完成项',cancel:'安全中断'}[a]}</button>`).join('')}<details><summary>错误和计划</summary><pre>${esc(JSON.stringify({errors:j.errors,plan:j.plan.items},null,2))}</pre></details></article>`).join('');document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>api('jobs/'+b.dataset.job+'/'+b.dataset.action,{}).then(refreshJobs).catch(notice));}
on('deliver',async()=>{if(!selected.size)throw Error('请选择审核通过的学生');await api('deliveries',{student_ids:[...selected]});show('deliveries');await refreshDeliveries();});on('exportIds',()=>saveFile('选中学号.json',{student_ids:[...selected]}));
async function refreshDeliveries(){$('deliveryList').innerHTML=(await api('deliveries')).map(b=>`<article><h3>${esc(b.id.slice(0,16))} · ${{prepared:'待实际交付',delivered:'已交付',cancelled:'已取消'}[b.status]}</h3><p>${b.items.length}人 · ${esc(b.at)}</p>${!b.historical&&b.status!=='cancelled'?`<a href="/api/v1/deliveries/${b.id}/download">下载学号命名照片包</a>`:''}${b.status==='prepared'?` <button data-batch="${b.id}" data-action="confirm">确认这批照片已经实际交付</button><button data-batch="${b.id}" data-action="cancel">取消交付包</button>`:''}<details><summary>查看学号</summary><p>${esc(b.items.map(x=>x.student_id).join('、'))}</p></details></article>`).join('');document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=async()=>{try{if(b.dataset.action==='confirm'&&!confirm('确认照片已实际发送给接收方？'))return;await api('deliveries/'+b.dataset.batch+'/'+b.dataset.action,{});await refresh();}catch(e){notice(e);}});}
async function init(){const token=new URLSearchParams(location.hash.slice(1)).get('token');if(token){await fetch('/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});history.replaceState(null,'',location.pathname);}const c=await api('config');config={...c.defaults,...c.saved};engineUrls=await api('engines/hivision/urls');drawConfig();$('workspace').textContent=(await api('health')).workspace;await refresh();const events=new EventSource('/api/v1/events');events.onmessage=()=>{refresh().catch(notice);};}
show('students');
init().catch(notice);

$('import').insertAdjacentHTML('beforeend','<article><h2>登记历史已交付名单</h2><p>例如此前已发送的483名学生。可直接粘贴已交付学号，未登记的学号会自动加入名单；只登记交付事实，不把当前照片标为审核通过。</p><textarea id="historicalIds" rows="5" aria-label="历史已交付学号"></textarea><input id="historicalReason" placeholder="交付依据，例如2026年8月办卡第一批"><label><input type="checkbox" id="historicalConfirmed">确认这些照片已经实际发送</label><button id="saveHistorical">登记已交付名单</button></article>');
on('saveHistorical',async()=>{await api('historical-deliveries',{student_ids:$('historicalIds').value.split(/[\s,，]+/).filter(Boolean),reason:$('historicalReason').value,confirmed_sent:$('historicalConfirmed').checked});await refresh();notice('历史交付名单已登记');});
document.addEventListener('keydown',event=>{if(!$('detail').open||['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;if(event.key==='ArrowLeft'){event.preventDefault();navigate(-1).catch(notice);}if(event.key==='ArrowRight'){event.preventDefault();navigate(1).catch(notice);}});
$('newVersion').onchange=()=>{plan=null;$('startJob').disabled=true;notice('处理范围已变化，请重新计算计划');};
on('replan',async()=>{await replan();$('startJob').disabled=false;});
on('process',async()=>{await replan();$('startJob').disabled=false;$('plan').showModal();});
document.querySelector('aside').insertAdjacentHTML('beforeend','<button id="exitApp">退出程序</button>');
on('exitApp',async()=>{await api('shutdown',{});notice('程序正在退出，可以关闭网页');});
$('detailNote').insertAdjacentHTML('afterend','<details id="detailSettings"><summary>调整处理参数，再次预览</summary><div id="previewFields" class="fields"></div><button id="savePreviewConfig">保存这些参数供批量处理</button></details>');
$('detailSettings').ontoggle=()=>{if(!$('detailSettings').open)return;$('previewFields').replaceChildren(...[...$('configFields').children].map(x=>x.cloneNode(true)));$('previewFields').querySelectorAll('[data-config]').forEach(e=>{const target=$('configFields').querySelector(`[data-config="${e.dataset.config}"]`);e.value=target.value;e.checked=target.checked;e.oninput=()=>{target.value=e.value;target.checked=e.checked;};});bindEngineTools($('previewFields'));};
on('savePreviewConfig',async()=>{config=await api('config',readConfig(),'PUT');notice('预览参数已保存为批量运行配置');});
