<template><iframe src="/legacy.html" title="StudentPhotoFlow后台" style="position:fixed;inset:0;width:100%;height:100%;border:0"></iframe></template>
<script setup>
import {ref,onMounted} from 'vue'
const pages=[{id:'students',label:'学生与审核'},{id:'import',label:'数据接入'},{id:'config',label:'处理配置'},{id:'jobs',label:'任务进度'},{id:'deliveries',label:'照片交付'}]
const page=ref('config'),cohort=ref(''),cohorts=ref([]),workspace=ref(''),urls=ref([]),selectedUrl=ref(''),message=ref(''),config=ref({hivision_url:'',hivision_timeout:120}),students=ref([]),query=ref(''),status=ref(''),selected=ref(new Set()),filtered=ref([]),labels={review:'待人工审核',approved:'审核通过待交付',delivered:'已交付'}
const api=async(path,opt={})=>{const r=await fetch('/api/v1/'+path,opt);const d=await r.json();if(!r.ok)throw Error(d.message||JSON.stringify(d));return d}
async function refresh(){const [h,c,u,ss]=await Promise.all([api('health'),api('config'),api('engines/hivision/urls'),api('students')]);workspace.value=h.workspace;students.value=ss;filtered.value=students.value.filter(s=>(!status.value||s.status===status.value)&&(!query.value||s.id.includes(query.value)));cohort.value=h.active_cohort;config.value={...c.defaults,...c.saved};urls.value=u;selectedUrl.value=urls.value.includes(config.value.hivision_url)?config.value.hivision_url:''}
function toggle(id){selected.value.has(id)?selected.value.delete(id):selected.value.add(id)}
function toggleAll(){filtered.value.forEach(s=>selected.value.add(s.id))}
async function batch(decision){if(!selected.value.size)return;await api('reviews/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_ids:[...selected.value],decision,reason:''})});selected.value.clear();await refresh()}
async function setCohort(){await api('cohort',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({cohort:cohort.value})})}
async function addUrl(){urls.value=await api('engines/hivision/urls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:config.value.hivision_url})});message.value='地址已保存到历史'}
async function removeUrl(){urls.value=await api('engines/hivision/urls?url='+encodeURIComponent(selectedUrl.value),{method:'DELETE'});selectedUrl.value='';message.value='历史地址已删除'}
async function testUrl(){message.value=JSON.stringify(await api('engines/hivision/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:config.value.hivision_url})}))}
async function checkUpdate(){const x=await api('update');message.value=x.version?'最新版本：'+x.version:'当前已是最新版本'}
onMounted(async()=>{const d=await api('cohorts');cohorts.value=d.cohorts;await refresh()})
</script>
<style scoped>
*{box-sizing:border-box}.app{display:flex;min-height:100vh;font:15px "Microsoft YaHei",sans-serif;color:#203348;background:#f4f7fa}aside{width:230px;padding:24px 16px;background:#143c46;color:#e1efee;position:fixed;inset:0 auto 0 0;overflow:auto}aside h2{margin:0 0 8px}aside p{color:#bcd4d4;overflow-wrap:anywhere}nav{display:grid;gap:8px;margin:28px 0}button,select,input{font:inherit;border:1px solid #b9cbd0;border-radius:7px;padding:9px;background:white;color:#204550}button{cursor:pointer;margin:6px 8px 6px 0}nav button{margin:0;text-align:left;background:transparent;color:white;border-color:#477078}nav button.active{background:#e2f4ef;color:#16463f}aside>button{width:100%}aside label{display:flex;flex-direction:column;gap:6px;margin-top:22px}aside select{width:100%}.workspace{margin-top:28px}main{margin-left:230px;width:calc(100% - 230px);padding:28px}header{display:flex;justify-content:space-between;align-items:center}.panel{background:white;border:1px solid #d7e1e4;border-radius:10px;padding:24px;max-width:1100px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.grid label,.history label{display:flex;flex-direction:column;gap:8px}.grid input{width:100%}.history{display:flex;gap:8px;align-items:end;border-top:1px solid #dfe7ee;margin-top:20px;padding-top:20px}.history label{flex:1}.delete{font-size:22px;color:#b42318;width:44px}.delete:disabled{opacity:.4}@media(max-width:700px){aside{position:static;width:100%}.app{display:block}main{margin:0;width:100%;padding:16px}.grid{grid-template-columns:1fr}}
</style>
