export const names={quality_enabled:'启用内置预检',auto_orient:'校正90/180/270度方向',check_grayscale:'黑白检查',check_face:'人脸检查',check_glare:'反光检查',check_recapture:'翻拍检查',background_mode:'图像处理引擎',background_color:'背景颜色',crop_enabled:'最终裁切并缩放',crop_width:'最终宽度（像素）',crop_height:'最终高度（像素）',hivision_url:'Hivision API地址',hivision_timeout:'API超时（秒）',hivision_width:'Hivision标准图宽',hivision_height:'Hivision标准图高',hivision_hd:'使用高清返回',hivision_face_align:'Hivision小角度对齐',hivision_matting_model:'Hivision抠图模型',hivision_face_model:'Hivision人脸模型',hivision_dpi:'打印DPI',stop_on_reject:'预检不通过时停止',grayscale_ratio_threshold:'黑白比例阈值',grayscale_delta_limit:'灰度色差阈值',face_confidence_threshold:'人脸置信度阈值',glare_ratio_threshold:'反光比例阈值',glare_luma_threshold:'过曝亮度阈值',recapture_score_threshold:'翻拍分数阈值',orientation_min_confidence:'方向最低置信度',orientation_confidence_margin:'旋转置信度优势',hivision_head_measure_ratio:'面部占比',hivision_head_height_ratio:'面部中心高度',hivision_top_distance_max:'头顶留白最大比例',hivision_top_distance_min:'头顶留白最小比例',hivision_brightness_strength:'亮度调整',hivision_contrast_strength:'对比度调整',hivision_sharpen_strength:'锐化调整',hivision_saturation_strength:'饱和度调整'};
export const groups=[
 ['原图预检','启用内置预检后执行以下检查；阈值与对应检查放在一起。',['quality_enabled','stop_on_reject','auto_orient','orientation_min_confidence','orientation_confidence_margin','check_grayscale','grayscale_ratio_threshold','grayscale_delta_limit','check_face','face_confidence_threshold','check_glare','glare_ratio_threshold','glare_luma_threshold','check_recapture','recapture_score_threshold']],
 ['背景处理','选择处理引擎；不处理背景时保留原背景。',['background_mode','background_color']],
 ['Hivision · 服务与模型','仅在选择 Hivision 引擎时使用。接口测试只检查连接，不上传照片。',['hivision_url','hivision_timeout','hivision_matting_model','hivision_face_model']],
 ['Hivision · 尺寸与构图','标准图尺寸与最终输出尺寸独立；高清返回仍会受最终裁切设置影响。',['hivision_width','hivision_height','hivision_dpi','hivision_hd','hivision_face_align','hivision_head_measure_ratio','hivision_head_height_ratio','hivision_top_distance_min','hivision_top_distance_max']],
 ['Hivision · 画面调整','保留 0 使用默认效果。建议先在单张照片上试处理。',['hivision_brightness_strength','hivision_contrast_strength','hivision_sharpen_strength','hivision_saturation_strength']],
 ['最终输出','在背景处理之后执行；开启后按以下宽高裁切并缩放。',['crop_enabled','crop_width','crop_height']]
];
export const choices={background_mode:['none','ai','quick','hivision'],hivision_matting_model:['modnet_photographic_portrait_matting','hivision_modnet','birefnet-v1-lite','rmbg-1.4','mnn_hivision_modnet'],hivision_face_model:['mtcnn','retinaface-resnet50','face_plusplus']};
export const engineNames={none:'不处理背景',ai:'本地 AI 抠图',quick:'快速纯色替换',hivision:'Hivision 服务'};
