// Run after cohort-acceptance and cohort-extended; synthetic IDs and photos only.
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
(async()=>{const out=process.argv[3],token=fs.readFileSync(process.argv[2],'utf8').match(/SPF_API_TOKEN=(.*)/)[1].trim();const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:1440,height:1000}}),checks=[];
const click=n=>p.getByRole('button',{name:n,exact:true}).click(),menu=n=>p.getByRole('menuitem',{name:n,exact:true}).click(),shot=n=>p.screenshot({path:out+'/'+n+'.png',fullPage:true});
const poll=async fn=>{for(let i=0;i<60;i++){if(await fn())return;await p.waitForTimeout(250);}throw Error('poll timed out');};
const ok=s=>{checks.push(s);fs.writeFileSync(out+'/final-checks.json',JSON.stringify(checks,null,2));console.log('PASS '+s);};
try{await p.goto(process.env.SPF_TEST_URL||'http://localhost:18971');await shot('11-login');await p.getByPlaceholder('访问令牌',{exact:true}).fill(token);await click('登录');await menu('学生与审核');assert.equal(await p.getByRole('button',{name:'退出程序',exact:true}).count(),0);
await click('单人补录');await p.getByRole('dialog',{name:'单人补录',exact:true}).getByRole('textbox').fill('00999');await p.getByRole('dialog',{name:'单人补录',exact:true}).getByRole('button',{name:'确定',exact:true}).click();await poll(async()=>await p.getByText('记录不存在',{exact:true}).count()>0);ok('exact single lookup rejects missing student without creating');
await click('单人补录');await p.getByRole('dialog',{name:'单人补录',exact:true}).getByRole('textbox').fill('00001');await p.getByRole('dialog',{name:'单人补录',exact:true}).getByRole('button',{name:'确定',exact:true}).click();const d=p.getByRole('dialog',{name:'学生 00001 · 流程与审核',exact:true});await d.getByRole('button',{name:'用当前配置试处理',exact:true}).click();await poll(async()=>(await d.innerText()).includes('试处理阶段结果（非正式成片）'));await shot('12-preview-stages');
await d.getByRole('button',{name:'审核通过当前成片'}).click();await poll(async()=>await d.getByRole('button',{name:'生成单人交付包'}).isEnabled());await d.getByRole('button',{name:'生成单人交付包'}).click();await poll(async()=>await d.getByRole('link',{name:'下载交付包'}).count()===2);const [down]=await Promise.all([p.waitForEvent('download'),d.getByRole('link',{name:'下载交付包'}).first().click()]);await down.saveAs(out+'/replacement-delivery.zip');await d.getByRole('button',{name:'确认已交付',exact:true}).click();await p.getByRole('dialog',{name:'确认已交付',exact:true}).getByRole('button',{name:'确定',exact:true}).click();await poll(async()=>await d.getByRole('button',{name:'确认已交付',exact:true}).count()===0);await d.getByRole('button',{name:'版本与操作记录'}).click();await shot('13-replacement-history');ok('replacement review/download/confirm retains two deliveries and versions; preview stages');await p.keyboard.press('Escape');
await menu('数据接入');await p.getByRole('textbox',{name:'学号名单',exact:true}).fill('00004');await click('校验并添加名单');await click('校验并添加名单');await menu('学生与审核');await p.getByPlaceholder('搜索学号').fill('00004');assert.equal(await p.getByTestId('student-table').locator('tbody tr').count(),1);await click('移入回收站');await p.getByRole('dialog',{name:'确认移入回收站'}).getByRole('button',{name:'确认移入完整范围'}).click();await menu('数据接入');await p.getByRole('textbox',{name:'学号名单',exact:true}).fill('00004');await click('校验并添加名单');await menu('系统设置');await click('恢复');await poll(async()=>await p.getByText('恢复冲突：同届学号或业务记录已存在，不会覆盖',{exact:true}).count()>0);await shot('14-restore-conflict');ok('duplicate roster remains unique; recycle restore conflict does not overwrite');
await menu('系统设置');await p.locator('.el-switch__core:visible').click();await click('保存系统设置');await poll(async()=>!await p.getByText('有未保存的系统设置',{exact:true}).count());await shot('15-retention-disabled');ok('automatic expiry can be disabled through settings');
await menu('数据接入');await p.getByRole('textbox',{name:'历史已交付学号',exact:true}).fill('00005');await p.getByPlaceholder('交付依据，例如已发送办卡第一批').fill('synthetic historical test');await p.locator('label.el-checkbox').filter({hasText:'确认这些照片已经实际发送'}).click();await click('登记已交付名单');await menu('照片交付');await shot('16-final-deliveries');ok('historical delivery page records fact without processing missing photos');
await menu('处理配置');await p.locator('[data-config="crop_width"] input:visible').fill('321');await p.locator('[data-config="crop_width"] input:visible').press('Tab');await click('保存配置');await poll(async()=>await p.getByText('运行配置已保存',{exact:true}).count()>0);const [cfg]=await Promise.all([p.waitForEvent('download'),click('导出配置 JSON')]);await cfg.saveAs(out+'/saved-config.json');assert.equal(JSON.parse(fs.readFileSync(out+'/saved-config.json','utf8')).crop_width,321);await shot('17-config');ok('global configuration saved and exported via page');await menu('任务进度');await shot('18-jobs');await menu('学生与审核');await p.getByPlaceholder('搜索学号').fill('');await shot('19-students');
}catch(e){await shot('final-failure');console.error(e);process.exitCode=1;}finally{await b.close();}})();
