const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert'),cp=require('child_process');
(async()=>{const root=process.argv[2],base=process.env.SPF_TEST_URL||'http://localhost:18981',token=fs.readFileSync(root+'/test.env','utf8').match(/SPF_API_TOKEN=(.*)/)[1].trim(),browser=await chromium.launch({headless:true}),p=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[];const click=n=>p.getByRole('button',{name:n,exact:true}).click(),menu=n=>p.getByRole('menuitem',{name:n,exact:true}).click(),poll=async fn=>{for(let i=0;i<160;i++){if(await fn())return;await p.waitForTimeout(250);}throw Error('poll timed out');},shot=async n=>{await p.waitForTimeout(300);await p.screenshot({path:root+'/'+n+'.png',fullPage:true});},ok=s=>{checks.push(s);fs.writeFileSync(root+'/task-checks.json',JSON.stringify(checks,null,2));console.log('PASS '+s);};
const req=async(path,body,method)=>{const r=await p.request.fetch(base+path,{method:method||(body?'POST':'GET'),data:body});assert.ok(r.ok(),await r.text());return r.json();};
const mock=async body=>{await fetch('http://127.0.0.1:18980/control',{method:'POST',body:JSON.stringify(body)});};const calls=async()=>await (await fetch('http://127.0.0.1:18980')).json();
let cid,api;
async function start(ids){await menu('学生与审核');await p.getByPlaceholder('搜索学号').fill(ids[0].slice(0,2));await p.locator('label.el-checkbox').filter({hasText:'全选筛选结果'}).click();await click('预览处理计划');await p.getByRole('dialog',{name:'本次执行计划'}).getByRole('button',{name:'按此计划开始处理'}).click();await menu('任务进度');const jobs=await req(api+'jobs');return jobs[0].id;}
const card=id=>p.locator('[data-job="'+id+'"]');
async function fixture(prefix){const ids=[1,2,3].map(i=>prefix+'00'+i);await req(api+'roster',{student_ids:ids});for(const id of ids){const r=await p.request.post(base+api+'students/'+id+'/photos',{multipart:{photo:{name:id+'.png',mimeType:'image/png',buffer:fs.readFileSync(root+'/synthetic.png')}}});assert.ok(r.ok(),await r.text());}await click('刷新');return ids;}
try{await p.goto(base);await p.getByPlaceholder('访问令牌',{exact:true}).fill(token);await click('登录');let settings=await req('/api/v1/settings');if(!settings.cohorts.some(c=>c.year==='2035'))settings.cohorts.push({year:'2035'});settings=await req('/api/v1/settings',settings,'PUT');cid=settings.cohorts.find(c=>c.year==='2035').id;api='/cohorts/'+cid+'/api/v1/';await req('/api/v1/config',{background_mode:'hivision',hivision_url:'http://host.docker.internal:18980',hivision_timeout:5},'PUT');await p.reload();await poll(async()=>await p.getByRole('combobox',{name:'当前届次'}).count()>0);await p.locator('.sidebar .el-select__wrapper').click();await p.getByRole('option',{name:'2035级',exact:true}).click();
await mock({delay:3,fail:false,calls:[]});let ids=await fixture('11'),jid=await start(ids);await poll(async()=>(await calls()).calls.length===1);await card(jid).getByRole('button',{name:'暂停',exact:true}).click();await poll(async()=>(await card(jid).innerText()).includes('正在暂停'));await shot('04-pausing');await poll(async()=>(await req(api+'jobs')).find(j=>j.id===jid).status==='paused');assert.equal((await calls()).calls.length,1);await card(jid).getByRole('button',{name:'继续未完成项'}).click();await poll(async()=>(await req(api+'jobs')).find(j=>j.id===jid).status==='completed');assert.equal((await calls()).calls.length,3);let j=(await req(api+'jobs')).find(j=>j.id===jid);assert.equal(j.counts.success,3);await poll(async()=>await card(jid).getByRole('button',{name:/^(暂停|继续未完成项|安全结束)$/}).count()===0);ok('SIMULATED: pause saves first item and schedules no next; resume calls remaining2 only');
await mock({delay:3,fail:false,calls:[]});ids=await fixture('12');jid=await start(ids);await poll(async()=>(await calls()).calls.length===1);await card(jid).getByRole('button',{name:'安全结束',exact:true}).click();await p.getByRole('dialog',{name:'安全结束',exact:true}).getByRole('button',{name:'安全结束',exact:true}).click();await poll(async()=>(await req(api+'jobs')).find(j=>j.id===jid).status==='cancelled');j=(await req(api+'jobs')).find(j=>j.id===jid);assert.equal(j.counts.success,1);assert.equal(j.counts.remaining,2);assert.equal((await calls()).calls.length,1);await poll(async()=>await card(jid).getByRole('button',{name:/^(暂停|继续未完成项|安全结束)$/}).count()===0);assert.equal((await p.request.post(base+api+'jobs/'+jid+'/resume',{data:{}})).status(),409);await shot('05-manual-ended');ok('SIMULATED: manual end processes only in-flight student, leaves2 unexecuted, resume API rejected');
await mock({delay:.1,fail:true,calls:[]});ids=await fixture('13');jid=await start(ids);await poll(async()=>(await req(api+'jobs')).find(j=>j.id===jid).status==='completed');await poll(async()=>await card(jid).getByTestId('job-errors').count()>0);const text=await card(jid).innerText();assert.ok(text.includes('失败 3 人')&&text.includes('503')&&text.includes('SIMULATED Hivision upstream unavailable'));assert.ok(!text.includes('mock-secret-do-not-display'));await shot('06-errors');ok('SIMULATED:3 HTTP503 failures shown by default with phase/reason; sensitive token redacted');
await mock({delay:8,fail:false,calls:[]});ids=await fixture('14');jid=await start(ids);await poll(async()=>(await req(api+'jobs')).find(j=>j.id===jid).status==='completed');j=(await req(api+'jobs')).find(j=>j.id===jid);assert.equal(j.counts.failed,3);ok('SIMULATED: configured5s timeout records failures without hanging');
fs.writeFileSync(root+'/tasks-fixture.json',JSON.stringify({cid,api},null,2));
}catch(e){await shot('tasks-failure');console.error(e);process.exitCode=1;}finally{await browser.close();}})();

